Correct path of route files
Azure-Samples/acme-fitness-store pull request #167
Opened 2023-09-19 08:15 UTC by dingmeng-xue

2023-09-19 09:25 UTC, jiec-msft commented on azure-spring-apps-enterprise/workshops/azure-spring-apps-enterprise/full/09-hol-3.1-deploy-backend-apps/README.md
> +    --routes-file .=./azure-spring-apps-enterprise/resources/json/routes/catalog-service.json
Shall we remove `=.`?

2023-09-19 12:42 UTC, dingmeng-xue commented on azure-spring-apps-enterprise/workshops/azure-spring-apps-enterprise/full/09-hol-3.1-deploy-backend-apps/README.md
> +    --routes-file .=./azure-spring-apps-enterprise/resources/json/routes/catalog-service.json
Thanks. Fixed it.

2023-09-20 00:05 UTC, anishp55 commented
i've updated the README for the first intermediate lab so that they are already in the `acme-fitness-store/azure-spring-apps-enterprise` directory

2023-09-20 01:21 UTC, anishp55 requested changes
please remove the `./azure-spring-apps-enterprise` and make it `./resources`
one of the PRs puts us into the `azure-spring-apps-enterprise` directory

2023-09-20 01:38 UTC, merged